### PR TITLE
Rewrite landing page with vuetify

### PR DESCRIPTION
**Pull request by nicolercl**
Rewrite landing page with Vuetify and modify login/logout functions to match style.
To test:
1) run devserver and go to localhost:8080/
2) clicking on the icon in the toolbar will show a navigation drawer like below.
3) the page links works as the original landing page and log in, logout as well.
螢幕快照 2019-06-28 下午6 32 45

### CODE REVIEW

**Comment by Sinyu104** [comment]
I check out to your branch and I see the result like this.
Is there something I forgot to do?
image

**Comment by Junochiu** [comment]
image
mine look same as Nicole's maybe it's because this is not on Nicole's Dev but in a new branch skillsearch?

**Comment by nicolercl** [comment]
Yes I opened a new branch named skill search. Did you remember to git fetch first?

**Comment by Sinyu104** [comment]
> Yes I opened a new branch named skill search. Did you remember to git fetch first?

I have done `git checkout skillsearch` before running local server.

**Comment by nicolercl** [comment]
Hmmm.. maybe run it like this?
`git fetch origin`
`git checkout -b skillsearch origin/skillsearch`
You might have to delete your local skillsearch branch first before you do this.

**Review by Junochiu — APPROVED** [review]

**Comment by 0xAlison** [comment]
mine works quite well. same as Nicole's ^^

**Pull request merged**
