### PR TITLE
Finish Aboutus description

### PR DESCRIPTION
**Pull request by Sinyu104**
Photos, icon, names, and self-introduction are all work.
image
It can show our English name is you hover on the photos.
image
And the icon will link to each one's facebook.

### CODE REVIEW

**Comment by Sinyu104** [comment]
image
It looks like this now!!

**Comment by nicolercl** [comment]
The display is ok, can you also resolve the conflicts with master branch?

**Comment by Sinyu104** [comment]
Sure. I have already solved the conflict.
Feel free to check it.

**Review by nicolercl — APPROVED** [review]
Looks good now!

**Pull request merged**
