### PR TITLE
Do a little change to our toolbar

### PR DESCRIPTION
**Pull request by Sinyu104**
#### It's now only on the public feed page.
image
#### If you click on the photo, it will show a drop-down list which links user-info and user-page.
image
If you guys feel okay, then I'll add it to other pages.
@Junochiu feel free to comment or edit.

### CODE REVIEW

**Comment by Junochiu** [comment]
image

**Comment by Junochiu** [comment]
this is how the navbar in my local looks like now~~

**Comment by Sinyu104** [comment]
Maybe you can make a PR so we can see your code and change ours.
Otherwise, would you want to add a profile photo?

**Comment by Junochiu** [comment]
I think it'll be cool to have a profile pic there!! I'm sorry that I didn't
make pull requests 🤦‍♀️ I was like jumping around the projects so there's
always things unfinished🤦‍♀️

Brandy Huang <notifications@github.com> 於 2019年7月15日 週一 01:56 寫道：

**Pull request closed without merging**
