### PR TITLE
Revert "Styled Text (Part2)-1"

### PR DESCRIPTION
**Pull request by Sinyu104**
Reverts codeu-su-19-team-48/team-48-codeu#47

### CODE REVIEW

**Comment by Sinyu104** [comment]
Uhhhh....
Actually, I want to merge your branch to master. 
But later on, I see you still have some function need to add. 
And then I pressed "rebase", try to stop the merging.
Maybe you can just edit the file you want to do next.
I'm not sure what I'll need to do. Should I approve this pull request?

**Comment by Junochiu** [comment]
Ha! I've never use rebase before~but I think maybe you could just merge them
into master if the present code is ok 🙂

**Comment by Junochiu** [comment]
The code is actually working, the photo part is that when you click on the
photo button, trying to upload a photo you'll find it not
functioning 😅
I found this site  :
https://gitbook.tw/chapters/branch/merge-with-rebase.html
Explaining quit clear ,hope it'll help ！ It also taught how to cancel a
rebase if needed. May be we can call out Angus for some suggestion🤔

**Comment by Sinyu104** [comment]
I closed the pull requests.
Since your code had merged to master already, I think it's okay that I close this pull request.

**Comment by Junochiu** [comment]
ok! 
This is a new experience XDD I'm still not so familiar with Git
 good luck for your finals!!

**Comment by Sinyu104** [comment]
Actually, I still have some problems with the map.
Maybe I just make pull request and get some suggestion from you guys.

**Comment by Junochiu** [comment]
Ok!not sure whether I can help or not I’ll try ha ! Maybe you can consider
using the Chat also?

Sinyu104 <notifications@github.com>於 2019年6月15日 週六，下午1:29寫道：

**Pull request closed without merging**
