### PR TITLE
add like button on the message card & a little styling

### PR DESCRIPTION
**Pull request by Sinyu104**
Hi everyone, I have met a problem for two days.
I tried to make a Vuetify card for each message, but I can't show on the correct way.
image

I have already checked the JS and HTML code and both of them are right.
image

### CODE REVIEW

**Comment by Junochiu** [comment]
Is the problem solved? Sorry that I saw the pull request just now…I can take a look for this later

**Comment by Sinyu104** [comment]
Not yet. That's okay, you can take a look later.😄😄😄

**Comment by nicolercl** [comment]
@Sinyu104 I'll take a look now. Oh and can you maybe update your branch with master before you make changes next time? Because console errors I fixed last time (Vue duplicate keys) are showing up.

**Comment by nicolercl** [comment]
Hi Brandy, I fixed the message display. It will show the messages you add now, you just have to modify the css and vuetify tags to make it the way you want it.

**Pull request closed without merging**
