### PR TITLE
adding geo chart to skill search, changing user info UI, add skill search button to side bar

### PR DESCRIPTION
**Pull request by Junochiu**
Hi guys, this is how it looks now:
1. go to http://localhost:8080/skill-search.html
2.enter some testing data in the form and summit
3.select a category in the button below
4.the result will show on the map
image
image
ps! this is the version with out datastore, Nicole and I will work together to bring them together~ and I am thinking finishing the card function after that :)

### CODE REVIEW

**Comment by Junochiu** [comment]
image
image
image
image

**Comment by Junochiu** [comment]
After filling up the user info then go to skill search page click the category and you'll see the map changed~

**Comment by nicolercl** [comment]
Hi I already added the skill search html to the navigation bar, it appears when you log in. Which one should we use? (Also, you spelled Search wrong. You can change that first?)

**Review by nicolercl — APPROVED** [review]
Works as expected!

**Pull request merged**
