### PR TITLE
add html page for public feed

### PR DESCRIPTION
**Pull request by Junochiu**
Hi! I added a html page for public feed, please check out :)

### CODE REVIEW

**Comment by nicolercl** [comment]
螢幕快照 2019-06-01 下午2 26 45
The html page works fine, though maybe you can run reformat code again? There's a one line change for me when I ran it~

**Comment by Junochiu** [comment]
> 螢幕快照 2019-06-01 下午2 26 45
> 
> The html page works fine, though maybe you can run reformat code again? There's a one line change for me when I ran it~

sure! was it line 48? If so, I've fixed it, please check out :)

**Review by Sinyu104 — APPROVED** [review]
#### I think it's okay to merge.

**Comment by Junochiu** [comment]
> #### I think it's okay to merge.

cool!I'll merge it then,thanks~

**Pull request merged**
