### PR TITLE
finishing up the text editing ckeditor and Styling -1

### PR DESCRIPTION
**Pull request by Junochiu**
Hi!
I block the image uploading function in Ckeditor for now, since it's not working yet.
I think I will discuss with Alison, and try to combine it with image part2 :)

### CODE REVIEW

**Comment by 0xAlison** [comment]
yes! I just check the current function u have committed so far. 
I think we can combine the functions together on week 6. (like add the image uploading function to the ckeditor)

**Comment by Junochiu** [comment]
Hi guys,
when I'm doing this part there's some weird thing happened, so I'd like to ask for your help to test on your computer :))
Ideally, it will look like this (following the example):
image
and the situation is that the code #content in css from codeu site doesn't work on my computer, the content sticked to the left instead standing at the center ((but actually it should work...maybe there's some bug I haven't figured out 😞 
image
To make it work on my computer, I change it into this:
image
but not pretty sure whether you will have the correct view or not ><
Thanks :))

**Comment by nicolercl** [comment]
The original code from codeu site produces the same result as yours on my computer too. I'll take a look.

**Review by nicolercl — APPROVED** [review]

**Comment by Sinyu104** [comment]
I'm the same with Nicole.

**Review by Sinyu104 — APPROVED** [review]

**Pull request merged**
